name: Development Environment

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Environment-specific variables
env:
  AWS_REGION: us-east-1
  ENVIRONMENT: dev

# Protection rules for development
protection_rules:
  - type: required_reviewers
    required_reviewers:
      teams: []
      users: []
  - type: wait_timer
    minutes: 0

# Environment secrets (set in GitHub repository settings)
# Required secrets:
# - AWS_ACCESS_KEY_ID: AWS access key for deployment
# - AWS_SECRET_ACCESS_KEY: AWS secret key for deployment
