name: Production Environment

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Environment-specific variables
env:
AWS_REGION: us-west-2
ENVIRONMENT: prod

# Protection rules for production
protection_rules:
  - type: required_reviewers
    required_reviewers:
      teams: []
      users: []
  - type: wait_timer
    minutes: 5  # 5-minute wait timer for production deployments
  - type: required_status_checks
    required_status_checks:
      contexts:
        - "Test GlobalInvoiceAI"
        - "Security Scan"

# Environment secrets (set in GitHub repository settings)
# Required secrets:
# - AWS_ACCESS_KEY_ID: AWS access key for deployment (production credentials)
# - AWS_SECRET_ACCESS_KEY: AWS secret key for deployment (production credentials)

# Note: Production deployments require manual approval and should use
# production AWS credentials with appropriate permissions
